version: '3.8'
services:
  users:
    container_name: users
    build: ./user
    volumes:
      - ./user/code:/usr/src/app
    networks:
      - users
    ports:
      - "3010:3010"
    working_dir: /usr/src/app
    command: bash -c "npm install && npm uninstall bcrypt && npm install bcrypt && npm run dev"
  gateway:
    container_name: apigateway
    build: ./apigateway
    volumes:
      - ./apigateway/code:/usr/src/app
    networks:
      - users
    ports:
      - "3011:3011"
    working_dir: /usr/src/app
    command: bash -c "npm install && npm run dev"

networks:
  users:
    driver: bridge