  name: Continuous integration
  on: [push]
  jobs:
    GitHub-Actions:
      runs-on: ubuntu-latest
      steps:
        - run: echo "Working..."
        - uses: actions/checkout@v3
        - run: npm ci

        - name: Install dependencies front-end
          run: cd front-end; npm ci

        - name: Run tests front-end
          run: cd front-end; npm test

        - name: Install playwright
          run: cd front-end; npx playwright install
