name: Continuous Integration

on:
  push:

jobs:
  GitHub-Actions:
    runs-on: ubuntu-latest

    steps:
      - run: echo "Working..."
      - uses: actions/checkout@v3

      - name: Install dependencies front-end
        run: cd front-end; npm ci

      - name: Install playwright
        run: cd front-end; npx playwright install

      - name: Run tests front-end
        run: cd front-end; npm test

      - name: Run ESLint
        run: cd front-end; npx eslint .
