  name: GitHub Actions Demo
  on: [push]
  jobs:
    GitHub-Actions:
      runs-on: ubuntu-latest
      steps:
        - run: echo "Working..."
        - uses: actions/checkout@v3
        - run: npm ci